### PR TITLE
Add split method

### PR DESCRIPTION
**Pull request by Janpot**
Adds a `.split` method analog to string

### CODE REVIEW

**Comment by XeCycle** [comment]
Sorry for the delay.

I am not convinced yet.  What you illustrated in the README can be (imo) better done by monkey-patching postgres to return multiple result sets; and I came up with no use cases besides your example.  Anyway this library is intended to be simple query builder, building up ONE query from pieces; I can think of no use to split the built query up.

Btw, is `concat` not just `.join("")`?

**Comment by Janpot** [comment]
The problem is not returning multiple result sets, the problem is that prepared statements can be only one statement. So you can't do a transaction like I made in the README unless you take out the interpolations or you query them separately.

I just like to keep as much unnecessary stuff out of my code, I think it's nicer and more readable for the next guy if I can write something like

``` js
return query(SQL`
  begin;
  lock table users in share row exclusive mode;
  insert into users (email)
    select ${email}
    where not exists (select * from users where email = ${email});
  commit;
`);
```

in stead of 

``` js
return Promise.map([
  SQL`begin`,
  SQL`lock table users in share row exclusive mode`,
  SQL`insert into users (email)
    select ${email}
    where not exists (select * from users where email = ${email})`,
  SQL`commit`
], query);
```

which is what I'm doing now.

I understand this library is just a query builder, but it's also a string template. I don't understand why you are so reluctant to implement the standard string functions on it.

**Comment by XeCycle** [comment]
No I prefer it not to be a full-featured string template.  What it builds is a query, that happens to be a string + an array of values, on which I do not expect standard string methods.

As for the multiple statements example, why not

``` js
transactionQueryAll(connection, [
  uniqueInsert("users", SQL`email`, SQL`${email}`)
  // maybe more
]);

function uniqueInsert(table, fields, values) {
  return [
    SQL`lock table ${SQL([table])} in share row exclusive mode`,
    SQL`insert into ${SQL([table])} (${fields})
      select ${values} where not exists (
        select * from ${SQL([table])} where (${fields}) = (${values})`
  ];
}
```

Basically there should be no long inline snippets of another language in one language, IMO.  That's why we all turn down on inline script tags, style tags, etc. in HTML.  The `MAX_UNREADABLE_LENGTH` is, admittedly, shorter in this template-like style than bare strings, but this does not mean writing everything inline is good.

**Comment by pauldraper** [comment]
More significantly, doing multi-statement parsing correctly would require heavy parsing, not a simple string find.

```javascript
`
SELECT * FROM entities WHERE name = '&amp;';
SELECT * FROM entities WHERE name = '&lt;';
`
```

**Pull request closed without merging**
